[project]
name = "democratic-process"
description = "CSC 21700 Final Project"
requires-python = ">= 3.12"

[tool.ruff]
target-version = "py312"
line-length = 120
select = ['E', 'F', 'W', 'A', 'PLC', 'PLE', 'PLW', 'I']
